import { useState, useMemo, useEffect } from "react";
import { format, parseISO, subDays } from "date-fns";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { FileDown, Clock } from "lucide-react";
import { track } from "@/lib/analytics";
import { useSymptomLogs } from "@/hooks/useSymptomLogs";
import { useMedications } from "@/hooks/useMedications";
import { useChildBaseline } from "@/hooks/useChildBaseline";
import { useTriggerLog } from "@/hooks/useTriggerLog";
import { useJourneyState } from "@/hooks/useJourneyState";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import type { JourneyStage } from "@/lib/types";
import AdvocateLayout from "./AdvocateLayout";
import { getReportHistory, addReportToHistory, VARIANT_LABELS } from "@/lib/reportHistory";
import { useActiveChild } from "@/hooks/useActiveChild";

// ─── Types ────────────────────────────────────────────────────────────────────

type Variant = "first_appointment" | "er_visit" | "follow_up";

// childId is accepted for future multi-child support; currently one implicit child per user.
type GenerateArgs = {
  childId: string;
  childName: string;
  childAge: string;
  visitDate: string;
  parentNotes: string;
};

// ─── PDF colours ─────────────────────────────────────────────────────────────

const HEAD: [number, number, number] = [55, 78, 55];
const URGENT: [number, number, number] = [160, 40, 30];

// ─── PDF helpers ─────────────────────────────────────────────────────────────

function fmtDate(d: string) {
  try { return format(parseISO(d + "T12:00:00"), "MMM d, yyyy"); } catch { return d; }
}

function section(doc: jsPDF, title: string, y: number, margin: number, color = HEAD): number {
  const pw = doc.internal.pageSize.getWidth();
  doc.setFillColor(...color);
  doc.rect(margin, y, pw - margin * 2, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.text(title.toUpperCase(), margin + 3, y + 4.8);
  doc.setTextColor(0);
  return y + 9;
}

function maybeNewPage(doc: jsPDF, y: number, needed = 40): number {
  if (y > doc.internal.pageSize.getHeight() - needed) { doc.addPage(); return 18; }
  return y;
}

function bodyText(doc: jsPDF, text: string, y: number, margin: number, fontSize = 9): number {
  const pw = doc.internal.pageSize.getWidth();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(fontSize);
  doc.setTextColor(40);
  const lines = doc.splitTextToSize(text, pw - margin * 2);
  doc.text(lines, margin, y);
  return y + lines.length * (fontSize * 0.35) + 3;
}

function pageFooters(doc: jsPDF, margin: number): void {
  const total = (doc.internal as unknown as { getNumberOfPages: () => number }).getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    const pw = doc.internal.pageSize.getWidth();
    const ph = doc.internal.pageSize.getHeight();
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(160);
    doc.text(`Page ${i} of ${total}`, pw - margin, ph - 6, { align: "right" });
    doc.text("Generated by PANS & PANDAS Tracker", margin, ph - 6);
  }
}

// ─── Variant 1: First appointment with a clinician ────────────────────────────

function generateFirstAppointmentPDF(
  args: GenerateArgs,
  logs30: ReturnType<typeof useSymptomLogs>["logs"],
) {
  const { childName, childAge, visitDate, parentNotes } = args;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const margin = 14;
  const pw = doc.internal.pageSize.getWidth();

  // Header banner
  doc.setFillColor(...HEAD);
  doc.rect(0, 0, pw, 36, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text("PANS & PANDAS: Clinical Reference", margin, 13);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(200, 230, 200);
  if (childName) doc.text(`Patient: ${childName}${childAge ? `, Age ${childAge}` : ""}`, margin, 21);
  doc.text(`Visit date: ${fmtDate(visitDate)}`, margin, 27);
  doc.text(`Generated: ${format(new Date(), "MMMM d, yyyy")}`, pw - margin, 27, { align: "right" });
  doc.setFontSize(8.5);
  doc.setTextColor(170, 210, 170);
  doc.text("Prepared for: First appointment with a clinician — for clinician reference", margin, 33);

  let y = 44;

  // What are PANS and PANDAS?
  y = section(doc, "What are PANS and PANDAS?", y, margin);
  y += 1;
  y = bodyText(doc, "PANS (Pediatric Acute-onset Neuropsychiatric Syndrome) and PANDAS (Pediatric Autoimmune Neuropsychiatric Disorders Associated with Streptococcal infections) are neuroinflammatory conditions in which a misdirected immune response causes sudden, dramatic changes in a child's behavior, mood, and cognition. The conditions are recognized by the National Institute of Mental Health.", y, margin);
  y += 2;
  y = bodyText(doc, 'The defining hallmark is sudden onset — symptoms appear within 24 to 72 hours, often described by parents as knowing "the exact day my child changed." This distinguishes PANS and PANDAS from primary psychiatric conditions, which typically develop gradually over weeks or months.', y, margin);
  y += 4;

  // PANS criteria
  y = maybeNewPage(doc, y, 65);
  y = section(doc, "PANS Research Consortium Diagnostic Criteria", y, margin);
  y += 1;
  autoTable(doc, {
    startY: y,
    head: [["Criterion", "Description"]],
    body: [
      ["1. Abrupt onset", "Sudden, dramatic onset of OCD or severely restricted food intake"],
      ["2. Concurrent symptoms", "Concurrent presence of additional neuropsychiatric symptoms from at least two of the following: anxiety, emotional lability/depression, irritability/aggression, behavioral regression, deterioration in school performance, sensory/motor abnormalities, somatic signs/sleep disturbances"],
      ["3. Not better explained", "Symptoms are not better explained by a known neurological or medical disorder"],
    ],
    margin: { left: margin, right: margin },
    styles: { fontSize: 8.5, cellPadding: 3, valign: "top" },
    headStyles: { fillColor: [80, 110, 80], textColor: 255, fontStyle: "bold", fontSize: 8 },
    columnStyles: { 0: { cellWidth: 38, fontStyle: "bold" }, 1: { cellWidth: "auto" } },
  });
  y = (doc as any).lastAutoTable.finalY + 6;

  // Swedo PANDAS criteria
  y = maybeNewPage(doc, y, 55);
  y = section(doc, "Swedo PANDAS Criteria (Original, 1998)", y, margin);
  y += 1;
  autoTable(doc, {
    startY: y,
    head: [["Criterion", "Description"]],
    body: [
      ["OCD or tic disorder", "Presence of OCD or a tic disorder that meets DSM criteria"],
      ["Prepubertal onset", "Onset between age 3 and puberty"],
      ["Episodic course", "Symptoms have an abrupt onset and episodic (relapsing-remitting) course"],
      ["Group A strep association", "Association with group A beta-hemolytic streptococcal infection (positive throat culture or elevated strep antibody titers)"],
      ["Neurological abnormalities", "Presence of neurological abnormalities during exacerbations (e.g., choreiform movements, tics, motoric hyperactivity)"],
    ],
    margin: { left: margin, right: margin },
    styles: { fontSize: 8.5, cellPadding: 3, valign: "top" },
    headStyles: { fillColor: [80, 110, 80], textColor: 255, fontStyle: "bold", fontSize: 8 },
    columnStyles: { 0: { cellWidth: 44, fontStyle: "bold" }, 1: { cellWidth: "auto" } },
  });
  y = (doc as any).lastAutoTable.finalY + 4;

  // References
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7.5);
  doc.setTextColor(130);
  doc.text("References: PANDAS Network — pandasnetwork.org | PANS Research Consortium — panspandasnetwork.org | NIMH — nimh.nih.gov", margin, y);
  y += 8;

  // Symptom timeline — new page
  doc.addPage();
  y = 14;
  y = section(doc, "Recent Symptom History (last 30 days)", y, margin);
  y += 1;
  const sorted = [...logs30].sort((a, b) => b.date.localeCompare(a.date));
  if (sorted.length === 0) {
    y = bodyText(doc, "No symptom logs recorded in the last 30 days.", y, margin);
  } else {
    autoTable(doc, {
      startY: y,
      head: [["Date", "OCD", "Anx", "Rage", "Tics", "Sleep", "Cog", "Notes"]],
      body: sorted.map((l) => [
        fmtDate(l.date),
        l.ocd ?? "—", l.anxiety ?? "—", l.rage ?? "—", l.tics ?? "—",
        l.sleep ?? "—", l.cognition ?? "—",
        l.notes ? l.notes.slice(0, 55) + (l.notes.length > 55 ? "…" : "") : "",
      ]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 8, cellPadding: 2.5 },
      headStyles: { fillColor: [80, 110, 80], textColor: 255, fontSize: 7.5 },
      columnStyles: {
        0: { cellWidth: 22 },
        1: { cellWidth: 9, halign: "center" }, 2: { cellWidth: 9, halign: "center" },
        3: { cellWidth: 9, halign: "center" }, 4: { cellWidth: 9, halign: "center" },
        5: { cellWidth: 9, halign: "center" }, 6: { cellWidth: 9, halign: "center" },
        7: { cellWidth: "auto" },
      },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7.5);
  doc.setTextColor(130);
  doc.text("Scale: 0 = none (or excellent for Sleep/Cognition), 5 = extreme (or very poor for Sleep/Cognition)", margin, y);
  y += 8;

  // What we are asking for
  y = maybeNewPage(doc, y, 80);
  y = section(doc, "What We Are Asking For Today", y, margin);
  y += 1;
  autoTable(doc, {
    startY: y,
    head: [["Test or Referral", "Purpose"]],
    body: [
      ["Throat culture or rapid strep test", "Rules out active group A strep infection"],
      ["ASO titer (Antistreptolysin O)", "Detects recent strep exposure; may be positive even if throat culture is negative"],
      ["Anti-DNase B titer", "More sensitive than ASO for detecting recent strep; both titers together improve diagnostic yield"],
      ["Urinalysis", "Urinary frequency and urgency can be a PANS symptom; baseline urinalysis is clinically useful"],
      ["Referral — Pediatric Neurology or Immunology", "PANS/PANDAS management may require specialist expertise in immunological treatment options"],
    ],
    margin: { left: margin, right: margin },
    styles: { fontSize: 8.5, cellPadding: 3, valign: "top" },
    headStyles: { fillColor: [80, 110, 80], textColor: 255, fontStyle: "bold", fontSize: 8 },
    columnStyles: { 0: { cellWidth: 60, fontStyle: "bold" }, 1: { cellWidth: "auto" } },
  });
  y = (doc as any).lastAutoTable.finalY + 6;

  if (parentNotes.trim()) {
    y = maybeNewPage(doc, y, 30);
    y = section(doc, "Parent / Caregiver Notes", y, margin);
    y += 2;
    y = bodyText(doc, parentNotes.trim(), y, margin);
  }

  pageFooters(doc, margin);
  const slug = childName ? childName.replace(/\s+/g, "-").toLowerCase() : "child";
  doc.save(`pans-first-appt-${slug}-${format(parseISO(visitDate + "T00:00:00"), "yyyyMMdd")}.pdf`);
}

// ─── Variant 2: ER visit ──────────────────────────────────────────────────────

function generateERVisitPDF(
  args: GenerateArgs,
  recentLogs: ReturnType<typeof useSymptomLogs>["logs"],
  medications: ReturnType<typeof useMedications>["medications"],
  triggers: ReturnType<typeof useTriggerLog>["entries"],
) {
  const { childName, childAge, visitDate, parentNotes } = args;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const margin = 14;
  const pw = doc.internal.pageSize.getWidth();

  // Urgent intake phrase box
  doc.setFillColor(...URGENT);
  doc.rect(0, 0, pw, 50, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255);
  const phrase = "My child had a sudden neuropsychiatric change.\nI am concerned about PANS or PANDAS.\nPlease consider an infectious workup.";
  doc.text(phrase, pw / 2, 20, { align: "center", lineHeightFactor: 1.6 });
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(255, 200, 200);
  doc.text(`Date: ${fmtDate(visitDate)}  |  Generated: ${format(new Date(), "MMMM d, yyyy")}`, pw / 2, 45, { align: "center" });

  let y = 58;

  // Patient info
  if (childName || childAge) {
    y = section(doc, "Patient Information", y, margin);
    y += 2;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(40);
    if (childName) { doc.text(`Name: ${childName}`, margin, y); y += 5; }
    if (childAge) { doc.text(`Age: ${childAge}`, margin, y); y += 5; }
    y += 2;
  }

  // Current symptoms — most recent log
  const mostRecent = [...recentLogs].sort((a, b) => b.date.localeCompare(a.date))[0];
  y = maybeNewPage(doc, y, 60);
  y = section(doc, `Current Symptoms${mostRecent ? ` (logged ${fmtDate(mostRecent.date)})` : ""}`, y, margin, URGENT);
  y += 1;
  if (mostRecent) {
    const CAT_ROWS: [string, number | null | undefined, string][] = [
      ["OCD / Intrusive Thoughts", mostRecent.ocd, "0 = none, 5 = extreme"],
      ["Anxiety", mostRecent.anxiety, "0 = none, 5 = extreme"],
      ["Rage / Irritability", mostRecent.rage, "0 = none, 5 = extreme"],
      ["Tics", mostRecent.tics, "0 = none, 5 = extreme"],
      ["Sleep Quality", mostRecent.sleep, "5 = excellent, 0 = very poor"],
      ["Cognitive Function", mostRecent.cognition, "5 = excellent, 0 = very poor"],
    ];
    autoTable(doc, {
      startY: y,
      head: [["Symptom Category", "Score", "Scale"]],
      body: CAT_ROWS.map(([cat, score, scale]) => [
        cat,
        score !== null && score !== undefined ? `${score}/5` : "Not logged",
        scale,
      ]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [...URGENT] as [number, number, number], textColor: 255, fontStyle: "bold", fontSize: 8.5 },
      columnStyles: {
        0: { cellWidth: 60 },
        1: { cellWidth: 18, halign: "center", fontStyle: "bold" },
        2: { cellWidth: "auto" },
      },
    });
    y = (doc as any).lastAutoTable.finalY + 4;
    if (mostRecent.notes) {
      y = bodyText(doc, `Parent notes from ${fmtDate(mostRecent.date)}: ${mostRecent.notes}`, y, margin, 8.5);
      y += 2;
    }
  } else {
    y = bodyText(doc, "No symptom log available. Please describe current symptoms verbally.", y, margin);
  }

  // Current medications
  const activeMeds = medications.filter((m) => !m.endDate || m.endDate >= visitDate);
  y = maybeNewPage(doc, y, 50);
  y = section(doc, "Current Medications", y, margin, URGENT);
  y += 1;
  if (activeMeds.length === 0) {
    y = bodyText(doc, "No current medications recorded.", y, margin);
    y += 2;
  } else {
    autoTable(doc, {
      startY: y,
      head: [["Medication", "Dose", "Started"]],
      body: activeMeds.map((m) => [
        m.name,
        `${m.dose}${m.frequency ? `, ${m.frequency}` : ""}`,
        fmtDate(m.startDate),
      ]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 8.5, cellPadding: 3 },
      headStyles: { fillColor: [...URGENT] as [number, number, number], textColor: 255, fontStyle: "bold", fontSize: 8 },
      columnStyles: { 0: { cellWidth: 60 }, 1: { cellWidth: "auto" }, 2: { cellWidth: 28 } },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Recent illness & exposure (last 30 days of triggers)
  const thirtyDaysAgo = format(subDays(new Date(), 30), "yyyy-MM-dd");
  const recentTriggers = triggers.filter((t) => t.date >= thirtyDaysAgo);
  y = maybeNewPage(doc, y, 50);
  y = section(doc, "Recent Illness & Exposure (Last 30 Days)", y, margin, URGENT);
  y += 1;
  if (recentTriggers.length === 0) {
    y = bodyText(doc, "No illness or exposure triggers logged in the last 30 days.", y, margin);
    y += 2;
  } else {
    autoTable(doc, {
      startY: y,
      head: [["Date", "Type", "Notes"]],
      body: recentTriggers
        .sort((a, b) => b.date.localeCompare(a.date))
        .map((t) => [fmtDate(t.date), t.category.replace(/_/g, " "), t.notes ?? ""]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 8.5, cellPadding: 3 },
      headStyles: { fillColor: [...URGENT] as [number, number, number], textColor: 255, fontStyle: "bold", fontSize: 8 },
      columnStyles: { 0: { cellWidth: 24 }, 1: { cellWidth: 42 }, 2: { cellWidth: "auto" } },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  if (parentNotes.trim()) {
    y = maybeNewPage(doc, y, 30);
    y = section(doc, "Parent / Caregiver Notes", y, margin, URGENT);
    y += 2;
    y = bodyText(doc, parentNotes.trim(), y, margin);
  }

  pageFooters(doc, margin);
  const slug = childName ? childName.replace(/\s+/g, "-").toLowerCase() : "child";
  doc.save(`pans-er-visit-${slug}-${format(parseISO(visitDate + "T00:00:00"), "yyyyMMdd")}.pdf`);
}

// ─── Variant 3: Follow-up with PANS provider ──────────────────────────────────

function generateFollowUpPDF(
  args: GenerateArgs,
  logs30: ReturnType<typeof useSymptomLogs>["logs"],
  medications: ReturnType<typeof useMedications>["medications"],
) {
  const { childName, childAge, visitDate, parentNotes } = args;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const margin = 14;
  const pw = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(...HEAD);
  doc.rect(0, 0, pw, 36, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.setTextColor(255, 255, 255);
  doc.text("PANS & PANDAS Symptom Report", margin, 13);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(200, 230, 200);
  if (childName) doc.text(`${childName}${childAge ? ` · Age ${childAge}` : ""}`, margin, 21);
  doc.text(`Visit date: ${fmtDate(visitDate)}`, margin, 27);
  doc.text(`Generated: ${format(new Date(), "MMMM d, yyyy")}`, pw - margin, 27, { align: "right" });
  doc.setFontSize(8);
  doc.setTextColor(170, 210, 170);
  doc.text("Follow-up with PANS provider — last 30 days", margin, 33);

  let y = 44;

  // Category averages
  const CAT_KEYS = ["ocd", "anxiety", "rage", "tics", "sleep", "cognition"] as const;
  const CAT_LABELS: Record<typeof CAT_KEYS[number], string> = {
    ocd: "OCD / Intrusive Thoughts", anxiety: "Anxiety", rage: "Rage / Irritability",
    tics: "Tics", sleep: "Sleep Quality (5=excellent)", cognition: "Cognitive / Focus (5=excellent)",
  };
  const sorted = [...logs30].sort((a, b) => b.date.localeCompare(a.date));
  const catStats = CAT_KEYS.map((k) => {
    const vals = sorted.map((l) => l[k]).filter((v): v is number => v !== null && v !== undefined);
    const avg = vals.length ? vals.reduce((s, v) => s + v, 0) / vals.length : 0;
    const worst = vals.length ? Math.max(...vals) : 0;
    return { key: k, label: CAT_LABELS[k], avg, worst };
  });

  y = section(doc, `Symptom Category Averages (${sorted.length} logged days)`, y, margin);
  y += 1;
  autoTable(doc, {
    startY: y,
    head: [["Symptom Category", "Avg Score", "Worst Day"]],
    body: catStats.map(({ label, avg, worst }) => [
      label,
      avg > 0 ? avg.toFixed(1) : "—",
      worst > 0 ? `${worst}/5` : "—",
    ]),
    margin: { left: margin, right: margin },
    styles: { fontSize: 8.5, cellPadding: 2.8, valign: "middle" },
    headStyles: { fillColor: [80, 110, 80], textColor: 255, fontStyle: "bold", fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: 24, halign: "center", fontStyle: "bold" },
      2: { cellWidth: 24, halign: "center" },
    },
  });
  y = (doc as any).lastAutoTable.finalY + 6;

  // 30-day log
  y = maybeNewPage(doc, y, 55);
  y = section(doc, "Daily Symptom Log (last 30 days)", y, margin);
  y += 1;
  if (sorted.length === 0) {
    y = bodyText(doc, "No symptom logs recorded in the last 30 days.", y, margin);
  } else {
    autoTable(doc, {
      startY: y,
      head: [["Date", "OCD", "Anx", "Rage", "Tics", "Sleep", "Cog", "Notes"]],
      body: sorted.map((l) => [
        fmtDate(l.date),
        l.ocd ?? "—", l.anxiety ?? "—", l.rage ?? "—", l.tics ?? "—",
        l.sleep ?? "—", l.cognition ?? "—",
        l.notes ? l.notes.slice(0, 55) + (l.notes.length > 55 ? "…" : "") : "",
      ]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 8, cellPadding: 2.5 },
      headStyles: { fillColor: [80, 110, 80], textColor: 255, fontSize: 7.5 },
      columnStyles: {
        0: { cellWidth: 22 },
        1: { cellWidth: 9, halign: "center" }, 2: { cellWidth: 9, halign: "center" },
        3: { cellWidth: 9, halign: "center" }, 4: { cellWidth: 9, halign: "center" },
        5: { cellWidth: 9, halign: "center" }, 6: { cellWidth: 9, halign: "center" },
        7: { cellWidth: "auto" },
      },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Medications
  const thirtyDaysAgo = format(subDays(new Date(), 30), "yyyy-MM-dd");
  const activeMeds = medications.filter((m) => !m.endDate || m.endDate >= thirtyDaysAgo);
  if (activeMeds.length > 0) {
    y = maybeNewPage(doc, y, 50);
    y = section(doc, "Current & Recent Medications", y, margin);
    y += 1;
    autoTable(doc, {
      startY: y,
      head: [["Medication", "Dose", "Started", "Ended"]],
      body: activeMeds.map((m) => [
        m.name, m.dose, fmtDate(m.startDate), m.endDate ? fmtDate(m.endDate) : "Ongoing",
      ]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 8.5, cellPadding: 3 },
      headStyles: { fillColor: [80, 110, 80], textColor: 255, fontStyle: "bold", fontSize: 8 },
      columnStyles: { 0: { cellWidth: 55 }, 1: { cellWidth: 35 }, 2: { cellWidth: 25 }, 3: { cellWidth: 25 } },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  if (parentNotes.trim()) {
    y = maybeNewPage(doc, y, 30);
    y = section(doc, "Parent / Caregiver Notes", y, margin);
    y += 2;
    y = bodyText(doc, parentNotes.trim(), y, margin);
  }

  pageFooters(doc, margin);
  const slug = childName ? childName.replace(/\s+/g, "-").toLowerCase() : "child";
  doc.save(`pans-follow-up-${slug}-${format(parseISO(visitDate + "T00:00:00"), "yyyyMMdd")}.pdf`);
}

// ─── Variant metadata ─────────────────────────────────────────────────────────

const VARIANTS: { id: Variant; title: string; description: string; defaultFor: JourneyStage[] }[] = [
  {
    id: "first_appointment",
    title: "First appointment with a new clinician",
    description: "Includes a one-page PANS/PANDAS primer, diagnostic criteria, your child's symptom timeline, and the specific tests and referrals you are requesting. For clinicians who may not be familiar with PANS.",
    defaultFor: ["exploring"],
  },
  {
    id: "er_visit",
    title: "ER visit",
    description: "One to two pages. Opens with the intake phrase, then current symptoms with severity, medications, and recent illness or exposure. Designed to be read quickly by an ER team.",
    defaultFor: ["in_crisis"],
  },
  {
    id: "follow_up",
    title: "Follow-up with our PANS provider",
    description: "Symptom category averages, the 30-day daily log, and current medications. Structured for a provider who already knows your child.",
    defaultFor: ["tracking"],
  },
];

function defaultVariantFor(stage: JourneyStage | null): Variant {
  if (stage === "in_crisis") return "er_visit";
  if (stage === "tracking") return "follow_up";
  return "first_appointment";
}

// ─── Page component ───────────────────────────────────────────────────────────

export default function AdvocateReports() {
  const { logs } = useSymptomLogs();
  const { medications } = useMedications();
  const { baseline } = useChildBaseline();
  const { entries: triggers } = useTriggerLog();
  const { journeyState } = useJourneyState();
  const { toast } = useToast();
  const activeChild = useActiveChild();

  const thirtyDaysAgo = format(subDays(new Date(), 30), "yyyy-MM-dd");
  const logs30 = useMemo(() => logs.filter((l) => l.date >= thirtyDaysAgo), [logs]);

  const [variant, setVariant] = useState<Variant>(() =>
    defaultVariantFor(null)
  );
  const [visitDate, setVisitDate] = useState(format(new Date(), "yyyy-MM-dd"));
  const [parentNotes, setParentNotes] = useState("");
  const [generating, setGenerating] = useState(false);
  const [history, setHistory] = useState(getReportHistory);

  // Update default variant once journey state loads
  useEffect(() => {
    if (journeyState?.journey_stage) {
      setVariant(defaultVariantFor(journeyState.journey_stage));
    }
  }, [journeyState?.journey_stage]);

  useEffect(() => {
    track("advocate_section_viewed", { section: "reports" });
  }, []);

  function handleGenerate() {
    setGenerating(true);
    try {
      const childId = activeChild?.id ?? "primary";
      const args: GenerateArgs = {
        childId,
        childName: baseline?.childName?.trim() ?? "",
        childAge: baseline?.childAge?.trim() ?? "",
        visitDate,
        parentNotes,
      };

      if (variant === "first_appointment") {
        generateFirstAppointmentPDF(args, logs30);
      } else if (variant === "er_visit") {
        generateERVisitPDF(args, logs30, medications, triggers);
      } else {
        generateFollowUpPDF(args, logs30, medications);
      }

      track("advocate_report_generated", {
        variant,
        journey_stage: journeyState?.journey_stage ?? null,
        child_id: activeChild?.id ?? null,
      });

      addReportToHistory({
        variant,
        visitDate,
        childName: baseline?.childName?.trim(),
      });
      setHistory(getReportHistory());

      toast({ title: "PDF downloaded", description: "Your report has been saved." });
    } catch {
      toast({ title: "Could not generate PDF", variant: "destructive" });
    } finally {
      setGenerating(false);
    }
  }

  return (
    <AdvocateLayout
      title="Reports for your appointment"
      subtitle="Choose the audience and generate a PDF. Each variant is designed to be read by a different person in a different context."
    >
      {/* Variant picker */}
      <div className="space-y-3 mb-8">
        {VARIANTS.map((v) => {
          const selected = variant === v.id;
          return (
            <button
              key={v.id}
              type="button"
              onClick={() => setVariant(v.id)}
              className="w-full text-left flex items-start gap-4 p-5 rounded-2xl border-2 transition-all"
              style={{
                borderColor: selected ? "var(--terracotta)" : "hsl(var(--border))",
                backgroundColor: selected
                  ? "hsl(var(--primary) / 0.05)"
                  : "hsl(var(--card))",
              }}
            >
              <div
                className="flex-shrink-0 w-5 h-5 rounded-full border-2 mt-0.5 flex items-center justify-center"
                style={{
                  borderColor: selected ? "var(--terracotta)" : "hsl(var(--border))",
                }}
              >
                {selected && (
                  <div
                    className="w-2.5 h-2.5 rounded-full"
                    style={{ backgroundColor: "var(--terracotta)" }}
                  />
                )}
              </div>
              <div>
                <p className="text-[15px] font-semibold text-foreground leading-snug">
                  {v.title}
                </p>
                <p className="text-[13px] text-muted-foreground mt-1 leading-relaxed">
                  {v.description}
                </p>
              </div>
            </button>
          );
        })}
      </div>

      {/* Options */}
      <div className="space-y-5 mb-8">
        <div>
          <Label htmlFor="visitDate" className="text-sm font-medium mb-1.5 block">
            Visit date
          </Label>
          <Input
            id="visitDate"
            type="date"
            value={visitDate}
            onChange={(e) => setVisitDate(e.target.value)}
            className="max-w-xs"
          />
        </div>
        <div>
          <Label htmlFor="parentNotes" className="text-sm font-medium mb-1.5 block">
            Parent notes <span className="text-muted-foreground font-normal">(optional — added to the last page)</span>
          </Label>
          <Textarea
            id="parentNotes"
            placeholder="Anything specific you want the clinician to know — recent changes, concerns, questions you want to ask..."
            value={parentNotes}
            onChange={(e) => setParentNotes(e.target.value)}
            rows={4}
          />
        </div>
      </div>

      {/* Generate */}
      <Button
        onClick={handleGenerate}
        disabled={generating}
        size="lg"
        className="gap-2"
        style={{ backgroundColor: "var(--terracotta)", color: "#fff" }}
      >
        <FileDown className="w-4 h-4" />
        {generating ? "Generating…" : "Download PDF"}
      </Button>

      <p className="text-xs text-muted-foreground mt-4 leading-relaxed">
        PDFs are generated locally — your data never leaves this device.
        {logs30.length === 0 && " No symptom logs in the last 30 days — the symptom timeline will show a placeholder."}
      </p>

      {/* Previously generated reports */}
      {history.length > 0 && (
        <div className="mt-10 pt-8 border-t border-border">
          <div className="flex items-center gap-2 mb-4">
            <Clock className="w-4 h-4 text-muted-foreground" />
            <h3 className="text-sm font-semibold text-foreground">Previously generated</h3>
          </div>
          <div className="space-y-2">
            {history.map((item) => (
              <div
                key={item.id}
                className="flex items-center justify-between gap-3 py-2.5 px-3 rounded-lg bg-muted/40 border border-border/50"
              >
                <div className="min-w-0">
                  <p className="text-[13px] font-medium text-foreground truncate">
                    {VARIANT_LABELS[item.variant]}
                    {item.childName ? ` · ${item.childName}` : ""}
                  </p>
                  <p className="text-[11px] text-muted-foreground mt-0.5">
                    Visit {format(parseISO(item.visitDate), "MMM d, yyyy")}
                    {" · Generated "}
                    {format(parseISO(item.generatedAt), "MMM d, yyyy")}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </AdvocateLayout>
  );
}
